language: c++

os:
  - linux
  - osx

# More recent debian for more recent Python (3.7)
dist: bionic

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - python3.7
  homebrew:
    packages:
      - python
      - llvm # Here is an attempt to get linking working on Darwin with LLVM

# The "Example Multi OS Build Matrix" in the Travis docs has this section, so
# I kept it.  Apparently listing a homebrew package above is not enough to
# install it.
# ... Actually, I'm going to omit it for now.  Other docs about MacOS indicate
# that the "homebrew" section will do the work.
# before_install:
#   - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update        ; fi
#   - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install python; fi

script:
  - make test